language: php

env:
    - SYMFONY_DEPRECATIONS_HELPER=weak

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: 7.4
          env: SYMFONY_VERSION='4.4.*'
        - php: 7.4
          env: SYMFONY_VERSION='5.0.*'
        - php: 7.4
          env: COMPOSER_FLAGS='--prefer-lowest'

php:
    - 7.3
    - 7.4

before_install:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi

install: composer update $COMPOSER_FLAGS --prefer-dist

script: vendor/bin/phpunit
